apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ .Values.namespace.name }}
  labels:
    app: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
        imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9093
          name: controller
        env:
        - name: KAFKA_NODE_ID
          value: "{{ .Values.kafka.kraft.nodeId }}"
        - name: KAFKA_PROCESS_ROLES
          value: "{{ .Values.kafka.config.processRoles }}"
        - name: KAFKA_LISTENERS
          value: "{{ .Values.kafka.config.listeners }}"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "{{ .Values.kafka.config.advertisedListeners }}"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "{{ .Values.kafka.config.listenerSecurityProtocolMap }}"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "{{ .Values.kafka.config.controllerListenerNames }}"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "{{ .Values.kafka.config.controllerQuorumVoters }}"
        - name: KAFKA_NUM_PARTITIONS
          value: "{{ .Values.kafka.config.numPartitions }}"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "{{ .Values.kafka.config.defaultReplicationFactor }}"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "{{ .Values.kafka.config.minInsyncReplicas }}"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "{{ .Values.kafka.config.offsetsTopicReplicationFactor }}"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "{{ .Values.kafka.config.transactionStateLogReplicationFactor }}"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "{{ .Values.kafka.config.transactionStateLogMinIsr }}"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "{{ .Values.kafka.config.logRetentionHours }}"
        - name: KAFKA_LOG_SEGMENT_BYTES
          value: "{{ .Values.kafka.config.logSegmentBytes }}"
        - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
          value: "{{ .Values.kafka.config.logRetentionCheckIntervalMs }}"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "{{ .Values.kafka.config.groupInitialRebalanceDelayMs }}"
        - name: CLUSTER_ID
          value: "{{ .Values.kafka.kraft.clusterId }}"
        command:
        - sh
        - -c
        - |
          # Format storage if not already formatted
          if [ ! -f /var/lib/kafka/data/meta.properties ]; then
            /opt/kafka/bin/kafka-storage.sh format -t ${CLUSTER_ID} -c /opt/kafka/config/kraft/server.properties
          fi
          # Start Kafka
          /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties \
            --override node.id=${KAFKA_NODE_ID} \
            --override process.roles=${KAFKA_PROCESS_ROLES} \
            --override listeners=${KAFKA_LISTENERS} \
            --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} \
            --override listener.security.protocol.map=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} \
            --override controller.listener.names=${KAFKA_CONTROLLER_LISTENER_NAMES} \
            --override controller.quorum.voters=${KAFKA_CONTROLLER_QUORUM_VOTERS} \
            --override num.partitions=${KAFKA_NUM_PARTITIONS} \
            --override default.replication.factor=${KAFKA_DEFAULT_REPLICATION_FACTOR} \
            --override min.insync.replicas=${KAFKA_MIN_INSYNC_REPLICAS} \
            --override offsets.topic.replication.factor=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR} \
            --override transaction.state.log.replication.factor=${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR} \
            --override transaction.state.log.min.isr=${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR} \
            --override log.retention.hours=${KAFKA_LOG_RETENTION_HOURS} \
            --override log.segment.bytes=${KAFKA_LOG_SEGMENT_BYTES} \
            --override log.retention.check.interval.ms=${KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS} \
            --override group.initial.rebalance.delay.ms=${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        resources:
          {{- toYaml .Values.kafka.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 45
          periodSeconds: 5
  {{- if .Values.kafka.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kafka.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.kafka.persistence.size }}
  {{- else }}
  volumes:
  - name: kafka-data
    emptyDir: {}
  {{- end }}
